export const catalogo = [
  {
    id: 1,
    titulo: "Inazuma Eleven",
    plataforma: "Nintendo DS",
    categoria: "Deportes",
    precioBase: 25.00,
    conservacion: "nuevo-precintado",
    stock: 4,
  },
  {
    id: 2,
    titulo: "Super Mario World",
    plataforma: "SNES",
    categoria: "Plataformas",
    precioBase: 39.99,
    conservacion: "usado-como-nuevo",
    stock: 3,
  },
  {
    id: 3,
    titulo: "Sonic the Hedgehog 2",
    plataforma: "MEGA DRIVE",
    categoria: "Plataformas",
    precioBase: 29.99,
    conservacion: "solo-cartucho",
    stock: 5,
  },
  {
    id: 4,
    titulo: "Final Fantasy VII",
    plataforma: "PS1",
    categoria: "RPG",
    precioBase: 44.99,
    conservacion: "usado-caja-danada",
    stock: 2,
  },
  {
    id: 5,
    titulo: "The Legend of Zelda: Ocarina of Time",
    plataforma: "N64",
    categoria: "Aventura",
    precioBase: 49.99,
    conservacion: "usado-como-nuevo",
    stock: 2,
  },
  {
    id: 6,
    titulo: "Pokémon Rojo",
    plataforma: "GAME BOY",
    categoria: "RPG",
    precioBase: 54.99,
    conservacion: "solo-cartucho",
    stock: 4,
  },
  {
    id: 7,
    titulo: "Street Fighter II Turbo",
    plataforma: "SNES",
    categoria: "Lucha",
    precioBase: 34.99,
    conservacion: "usado-caja-danada",
    stock: 3,
  },
  {
    id: 8,
    titulo: "Tekken 3",
    plataforma: "PS1",
    categoria: "Lucha",
    precioBase: 27.99,
    conservacion: "usado-como-nuevo",
    stock: 6,
  },
  {
    id: 9,
    titulo: "Mario Kart 64",
    plataforma: "N64",
    categoria: "Deportes",
    precioBase: 47.99,
    conservacion: "nuevo-precintado",
    stock: 1,
  },
  {
    id: 10,
    titulo: "Tetris",
    plataforma: "GAME BOY",
    categoria: "Puzzle",
    precioBase: 24.99,
    conservacion: "usado-caja-danada",
    stock: 2,
  },
  {
    id: 11,
    titulo: "Streets of Rage 2",
    plataforma: "MEGA DRIVE",
    categoria: "Lucha",
    precioBase: 42.99,
    conservacion: "solo-cartucho",
    stock: 3,
  },
  {
    id: 12,
    titulo: "Mario Kart DS",
    plataforma: "Nintendo DS",
    categoria: "Deportes",
    precioBase: 32.99,
    conservacion: "usado-como-nuevo",
    stock: 4,
  },
]